import type { Metadata } from "next";
import "./globals.css";
import { AppWrapper } from "./Context/AppointContext";
export const metadata: Metadata = {
  title: "HOSPITAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="fa">
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
